// react-app/src/About.js
import React from 'react';

const About = () => (
  <div className="content-container">
    <div className="content-title-group not-found">
      <h2 className="title">Product Wish List</h2>
      <p>
        This project was created to help represent a fundamental app written
        with React. The shopping theme is used throughout the app.
      </p>
      <br />
      <h2 className="title">Resources</h2>
      <ul>
        <li>
          <a href="https://github.com/madhav5589/azure-static-web-app-demo">
            Code in GitHub
          </a>
        </li>
      </ul>
    </div>
  </div>
);

export default About;

// vue-app/src/views/about.vue
<template>
  <div class="content-container">
    <div class="content-title-group not-found">
      <h2 class="title">Product Wish List</h2>
      <p>
        This project was created to help represent a fundamental app written
        with Vue. The shopping theme is used throughout the app.
      </p>
      <br />
      <h2 class="title">Resources</h2>
      <ul>
        <li>
          <a href="https://github.com/madhav5589/azure-static-web-app-demo">
            Code in GitHub
          </a>
        </li>
      </ul>
    </div>
  </div>
</template>
